### ISSUE TITLE
TabularInline does not display the last data and missing "add another {model}" link

### ISSUE THREAD

**Issue by fengyouchao** [farridav/django-jazzmin#125] opened 2020-08-24 02:39 UTC
## 1. When a `TabularInline` does not have add permission, the last inline data will not be displayed.

Example:

```python
class AnswerInline(admin.TabularInline):
    extra = 0
    model = Answer

    def has_add_permission(self, request, obj=None):
        return False


@admin.register(Question)
class QuestionAdmin(admin.ModelAdmin):
    inlines = (AnswerInline,)
```
If a `question` has two `answers`, but only the first answer will be displayed in `QuestionAdmin`.

## 2. Missing "add another {model}" link

`TabularInline` does not display the "add another {model}" link even if it has add permission.

**Comment by farridav** [comment] 2020-08-29 15:55
Any chance of a branch that either demonstrates the problem, or fixes it ?

As with the other PR its been difficult to reproduce, ideally we would reproduce the admin setup in our test_app ..

**Comment by TysonRV** [comment] 2020-10-06 12:04
@fengyouchao I've sent a fix (#165) for the first of your points.

For some reason, I couldn't reproduce the second bullet point. Since the issue was for a while ago, I guess it's been resolved already? Let me know if you are seeing it again

**Comment by TysonRV** [comment] 2020-10-06 16:50
@fengyouchao It'll be finally fixed on #167, as @farridav found a more elegant solution to that particular issue

**Closed** 2020-10-06 21:25 UTC
