### ISSUE TITLE
Django-jazzmin - Logout

### ISSUE THREAD

**Issue by HamaBarhamou** [farridav/django-jazzmin#524] opened 2023-12-26 20:24 UTC
hello, here's a [conversation](https://forum.djangoproject.com/t/django-jazzmin-logout/26110) that seems to evoke a problem that can be corrected here.

**Comment by idan-krayon** [comment] 2023-12-26 20:37
We implemented this fix on our base code without forking the Jazzmin codebase with the help of the devs in the conversation above. I can confirm there is a problem with the logout button. instead of sending POST /logout, it sends GET /logout.

**Comment by Malith-Rukshan** [comment] 2024-03-01 15:13
Since [django-5](https://docs.djangoproject.com/en/5.0/releases/5.0), you need to do this through a POST request. To fix this, replace [logout dropdown at jazzmin base.html](https://github.com/farridav/django-jazzmin/blob/586e81f204033add57b67f657e43681801356a9a/jazzmin/templates/admin/base.html#L163-L165) with this :- 

```
<form action="{% url 'admin:logout' %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="dropdown-item">
        <i class="fas fa-users mr-2"></i> {% trans 'Log out' %}
    </button>
</form>
```

![Django Admin Logout Fixes](https://github.com/farridav/django-jazzmin/assets/85282650/8fc5223e-3450-45cc-9a27-3946ff802ce1)
![Django Admin Logout Fixed](https://github.com/farridav/django-jazzmin/assets/85282650/1314ecc6-8ed7-4b41-b5ba-6b0f02b4d9f6)

**Comment by jamesgilmorelyst** [comment] 2024-03-22 12:21
Duplicate issue - https://github.com/farridav/django-jazzmin/issues/522
PR raised (x2) - https://github.com/farridav/django-jazzmin/pull/523 / https://github.com/farridav/django-jazzmin/pull/537

**Comment by jamesgilmorelyst** [comment] 2024-03-23 14:47
a PR was merged today (https://github.com/farridav/django-jazzmin/pull/544) to fix this issue. A new release will be needed to release this fix.

**Comment by HamaBarhamou** [comment] 2024-03-23 20:33
> Hé@HamaBarhamou, un PR a été fusionné aujourd'hui ( #544 ) pour résoudre ce problème. Une nouvelle version sera nécessaire pour publier ce correctif.

great, so we can close this problem

**Comment by PacificGilly** [comment] 2024-04-18 19:24
Apologies for the delay, but we've release the fix to resolve the logout issue now:

- https://github.com/farridav/django-jazzmin/releases/tag/v3.0.0

If you are still supporting an older version of Python (<3.8) or Django (<4) then we also have release a fix for this version as well:
- https://github.com/farridav/django-jazzmin/releases/tag/v2.6.2

**Closed by PacificGilly** 2024-04-18 19:24 UTC
Labels: bug, Duplicate

**Comment by HamaBarhamou** [comment] 2024-04-19 09:32
> Toutes nos excuses pour le retard, mais nous avons publié le correctif pour résoudre le problème de déconnexion :
> 
> * https://github.com/farridav/django-jazzmin/releases/tag/v3.0.0
> 
> Si vous prenez toujours en charge une ancienne version de Python (<3.8) ou de Django (<4), nous avons également publié un correctif pour cette version :
> 
> * https://github.com/farridav/django-jazzmin/releases/tag/v2.6.2

great. glad to have helped
